CREATE TABLE joined_fight (
	id INT PRIMARY KEY NOT NULL,
	fight_id VARCHAR,
	result VARCHAR,
	fighter_1 VARCHAR,
	fighter_1_kd INT,
	fighter_1_nsub INT,
	fighter_1_sig_abs INT,
	fighter_1_sig_att INT,
	fighter_1_sig_adef INT,
	fighter_1_sig_land INT,
	fighter_2 VARCHAR,
	fighter_2_kd INT,
	fighter_2_nsub INT,
	fighter_2_sig_abs INT,
	fighter_2_sig_att INT,
	fighter_2_sig_adef INT,
	fighter_2_sig_land INT,
	winner VARCHAR,
	decision_method VARCHAR,
	fight_duration_lastrnd INT,
	fight_duration_lastrnd_time VARCHAR,
	time_format VARCHAR,
	weight_class VARCHAR,
	date INT,
	fight_length_min FLOAT
);

CREATE TABLE fighters (
	id  INT PRIMARY KEY NOT NULL,
	dob INT,
	height VARCHAR,
	n_draw INT,
	n_loss INT,
	n_win INT,
	name VARCHAR,
	reach INT,
	sig_str_abs_pM FLOAT,
	sig_str_def_pct FLOAT,
	sig_str_land_pM FLOAT,
	sig_str_land_pct FLOAT,
	stance VARCHAR,
	sub_avg FLOAT,
	td_avg FLOAT,
	td_def_pct FLOAT,
	td_land_pct FLOAT,
	weight VARCHAR,
	total_fights INT
);